from __future__ import annotations

from mltree2code.generators.base import BaseGenerator
from mltree2code.ir import Leaf, Node, TreeIR


class CppGenerator(BaseGenerator):
    language = "cpp"
    file_extension = ".cpp"

    def _float_type(self) -> str:
        return "double" if self.options.float_type == "double" else "float"

    def _suffix(self) -> str:
        return "" if self.options.float_type == "double" else "f"

    def emit_preamble(self, tree: TreeIR) -> None:
        if self.options.include_comments:
            self.add("// Auto-generated by mltree2code")
            self.add(
                f"// features={tree.n_features} depth={tree.depth()} leaves={tree.leaf_count()}"
            )
            self.add("")
        if self.options.header:
            self.add("#include <array>")
            self.add("#include <cstddef>")
            self.add("")
        ns = self.options.namespace
        if ns:
            self.add(f"namespace {ns} {{")
            self.add("")

    def emit_epilogue(self, tree: TreeIR) -> None:
        if self.options.namespace:
            self.add("")
            self.add(f"}}  // namespace {self.options.namespace}")

    def emit_function(self, tree: TreeIR) -> None:
        name = self.options.function_name
        ft = self._float_type()
        if tree.is_classifier and self.options.probabilities:
            n = tree.n_classes or 1
            self.add(f"void {name}(const {ft}* x, {ft}* out) {{")
            self.add(f"{self.ind(1)}// writes {n} probabilities into out")
            self.visit(tree.root, tree, 1)
            self.add("}")
        elif tree.is_classifier:
            self.add(f"int {name}(const {ft}* x) {{")
            self.visit(tree.root, tree, 1)
            self.add("}")
        else:
            self.add(f"{ft} {name}(const {ft}* x) {{")
            self.visit(tree.root, tree, 1)
            self.add("}")

    def emit_leaf(self, leaf: Leaf, tree: TreeIR, level: int) -> None:
        ind = self.ind(level)
        suf = self._suffix()
        if tree.is_classifier and self.options.probabilities and leaf.probabilities:
            for i, p in enumerate(leaf.probabilities):
                self.add(f"{ind}out[{i}] = {self.fmt_float(p, suf)};")
            self.add(f"{ind}return;")
        elif tree.is_classifier:
            self.add(f"{ind}return {int(leaf.prediction)};")
        else:
            self.add(f"{ind}return {self.fmt_float(float(leaf.prediction), suf)};")

    def emit_node(self, node: Node, tree: TreeIR, level: int) -> None:
        ind = self.ind(level)
        feat = self.feat(node.feature)
        thr = self.fmt_float(node.threshold, self._suffix())
        self.add(f"{ind}if ({feat} <= {thr}) {{")
        self.visit(node.left, tree, level + 1)
        self.add(f"{ind}}} else {{")
        self.visit(node.right, tree, level + 1)
        self.add(f"{ind}}}")
