from __future__ import annotations

from mltree2code.generators.base import BaseGenerator
from mltree2code.ir import Leaf, Node, TreeIR


class JavaScriptGenerator(BaseGenerator):
    language = "javascript"
    file_extension = ".js"

    def emit_preamble(self, tree: TreeIR) -> None:
        if self.options.include_comments:
            self.add("// Auto-generated by mltree2code")
            self.add(
                f"// features={tree.n_features} depth={tree.depth()} leaves={tree.leaf_count()}"
            )
            self.add("")

    def emit_function(self, tree: TreeIR) -> None:
        name = self.options.function_name
        self.add(f"function {name}(x) {{")
        self.visit(tree.root, tree, 1)
        self.add("}")
        self.add("")
        self.add(f"module.exports = {{ {name} }};")

    def emit_leaf(self, leaf: Leaf, tree: TreeIR, level: int) -> None:
        ind = self.ind(level)
        if tree.is_classifier and self.options.probabilities and leaf.probabilities:
            probs = ", ".join(self.fmt_float(p) for p in leaf.probabilities)
            self.add(f"{ind}return [{probs}];")
        elif tree.is_classifier:
            self.add(f"{ind}return {int(leaf.prediction)};")
        else:
            self.add(f"{ind}return {self.fmt_float(float(leaf.prediction))};")

    def emit_node(self, node: Node, tree: TreeIR, level: int) -> None:
        ind = self.ind(level)
        feat = self.feat(node.feature)
        thr = self.fmt_float(node.threshold)
        self.add(f"{ind}if ({feat} <= {thr}) {{")
        self.visit(node.left, tree, level + 1)
        self.add(f"{ind}}} else {{")
        self.visit(node.right, tree, level + 1)
        self.add(f"{ind}}}")
